name: formula_parser
description: A parsing library to parse formulas and evaluate like we use in excel or spreadsheets.
version: 2.0.1
repository: "https://github.com/sriram10/formula-parser-dart"

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  petitparser: ^5.4.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.8
